name: 'move-tags'
description: 'Moving tag'
author: 'snsina'
inputs:
  tag_name:
    required: true
  commit_sha:
    required: true
  token:
    required: true
outputs:
  cache-hit:
    description: 'A blah value to indicate an exact match was found for the primary key'
  text:
    description: 'A boolean value to indicate an exact match was found for the primary key'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.tag_name }}
    - ${{ inputs.commit_sha }}
    - ${{ inputs.token }}
